# Generated by Django 3.2.9 on 2021-12-12 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_blog_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('blog_date',)},
        ),
        migrations.AlterField(
            model_name='post',
            name='blog_date',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
