# Generated by Django 3.2.9 on 2021-12-12 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_blog_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='blog_slug',
            new_name='slug',
        ),
    ]
