# Generated by Django 3.2.9 on 2021-12-12 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_blog_slug_post_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-blog_date',)},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='slug',
            new_name='blog_slug',
        ),
    ]
